export enum Events {
  ON_HI = "ON_HI",
  // user related
  ON_STATUS = "ON_STATUS",
  ON_NEW_USER = "ON_NEW_USER",

  // thought related
  ON_DELETE_THOUGHT = "ON_DELETE_THOUGHT",
  ON_UPDATE_THOUGHT = "ON_UPDATE_THOUGHT",
  ON_CREATE_THOUGHT = "ON_CREATE_THOUGHT",
  ON_USER_UPDATE = "ON_USER_UPDATE",

  // notifications related
  ON_NEW_NOTIFICATION = "ON_NEW_NOTIFICATION",
  ON_DELETE_NOTIFICATION = "ON_DELETE_NOTIFICATION",
  ON_READ_NOTIFICATION = "ON_READ_NOTIFICATION",
  ON_UNREAD_NOTIFICATION = "ON_UNREAD_NOTIFICATION",

  // comment related

  ON_COMMENT_DELETE = "ON_COMMENT_DELETE",
  ON_COMMENT_UPDATE = "ON_COMMENT_UPDATE",
  ON_CREATE_COMMENT = "ON_CREATE_COMMENT",

  // reply related
  ON_REPLY_UPDATE = "ON_REPLY_UPDATE",
  ON_REPLY_DELETE = "ON_REPLY_DELETE",
  ON_REPLY_CREATE = "ON_REPLY_CREATE",
}

export const serverURL = new URL("http://localhost:3001/");
