export enum Events {
  ON_HI = "ON_HI",
  ON_STATUS = "ON_STATUS",
  ON_DELETE_THOUGHT = "ON_DELETE_THOUGHT",
  ON_UPDATE_THOUGHT = "ON_UPDATE_THOUGHT",
  ON_CREATE_THOUGHT = "ON_CREATE_THOUGHT",
  ON_USER_UPDATE = "ON_USER_UPDATE",
  ON_NEW_USER = "ON_NEW_USER",
  ON_CREATE_COMMENT = "ON_CREATE_COMMENT",
  ON_NEW_NOTIFICATION = "ON_NEW_NOTIFICATION",
  ON_DELETE_NOTIFICATION = "ON_DELETE_NOTIFICATION",
  ON_READ_NOTIFICATION = "ON_READ_NOTIFICATION",
  ON_UNREAD_NOTIFICATION = "ON_UNREAD_NOTIFICATION",
}

export const serverURL = new URL("http://localhost:3001/");
